In [2]:
import os
import sys
os.environ['_JAVA_OPTIONS'] = '-Djava.security.manager=allow -Duser.name=julianromero'
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

from pyspark.sql import SparkSession
import pyspark.pandas as ps
spark = SparkSession.builder.appName("SparkSession").getOrCreate()

from utils.sql_manager import SQLManager
sql_manager = SQLManager(queries_dir='../queries')

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(
Picked up _JAVA_OPTIONS: -Djava.security.manager=allow -Duser.name=julianromero
Picked up _JAVA_OPTIONS: -Djava.security.manager=allow -Duser.name=julianromero
WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/02/17 18:22:35 WARN Utils: Your hostname, MacBook-Air-de-Julian.local, resolves to a loopback address: 127.0.0.1; using 10.100.136.26 instead (on interface en0)
26/02/17 18:22:35 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/02/17 18:22:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
#Archivos
hosp_adm = spark.read.csv("../data/nw_hosp/admissions.csv", header=True, inferSchema=True)
icu_stays = spark.read.csv("../data/nw_icu/icustays.csv", header=True, inferSchema=True)
patients = spark.read.csv("../data/nw_hosp/patients.csv", header=True, inferSchema=True)
chart_events = spark.read.csv("../data/nw_icu/chartevents.csv", header=True, inferSchema=True)
lab_events = spark.read.csv("../data/nw_hosp/labevents.csv", header=True, inferSchema=True)
procedure_events = spark.read.csv("../data/nw_icu/procedureevents.csv", header=True, inferSchema=True)
diagnoses_icd = spark.read.csv("../data/nw_hosp/diagnoses_icd.csv", header=True, inferSchema=True)

In [4]:
#Vistas temporales
hosp_adm.createOrReplaceTempView("admissions")
icu_stays.createOrReplaceTempView("icu_stays")
patients.createOrReplaceTempView("patients")
chart_events.createOrReplaceTempView("chart_events")
lab_events.createOrReplaceTempView("lab_events")
procedure_events.createOrReplaceTempView("procedure_events")
diagnoses_icd.createOrReplaceTempView("diagnoses_icd")

In [7]:
hosp_adm_data = sql_manager.execute(spark, 'initial_data/admissions.sql')
hosp_adm_data.createOrReplaceTempView("hosp_adm_data")

icu_stays_data = sql_manager.execute(spark, 'initial_data/icu_stays.sql')
icu_stays_data.createOrReplaceTempView("icu_stays_data")

chart_events_data = sql_manager.execute(spark, 'initial_data/chart_events.sql')
chart_events_data.createOrReplaceTempView("chart_events_data")

patients_data = sql_manager.execute(spark, 'initial_data/patients.sql')
patients_data.createOrReplaceTempView("patients_data")

lab_events_data = sql_manager.execute(spark, 'initial_data/lab_events.sql')
lab_events_data.createOrReplaceTempView("lab_events_data")

procedure_events_data = sql_manager.execute(spark, 'initial_data/procedure_events.sql')
procedure_events_data.createOrReplaceTempView("procedure_events_data")

In [99]:
icu_stays.show(5)
stays_count = spark.sql("select subject_id, count(*) as num_stays from icu_stays group by subject_id order by num_stays desc")
stays_count.show(5)
icu_stays_data

+----------+--------+--------+--------------+-------------+-------------------+-------------------+------------------+
|subject_id| hadm_id| stay_id|first_careunit|last_careunit|             intime|            outtime|               los|
+----------+--------+--------+--------------+-------------+-------------------+-------------------+------------------+
|  30000238|44714428|59801852|         CTICU|        CTICU|2195-10-14 15:12:00|2195-10-16 14:32:00|1.9722222222222223|
|  30000246|40653169|55154064|          CICU|         CICU|2104-05-05 18:23:00|2104-05-07 14:26:00|1.8354166666666667|
|  30000521|46912110|58492193|          SICU|         SICU|2188-04-17 16:46:00|2188-04-18 18:16:00|            1.0625|
|  30000590|44608425|50707570|         NSICU|        NSICU|2177-12-09 12:01:00|2177-12-10 16:43:00|1.1958333333333333|
|  30000828|40615900|57131111|          MICU|          CCU|2124-10-17 23:12:00|2124-10-18 11:57:00|           0.53125|
+----------+--------+--------+--------------+-------------+-------------------+-------------------+------------------+
only showing top 5 rows
+----------+---------+
|subject_id|num_stays|
+----------+---------+
|  39585304|       20|
|  35136418|       14|
|  37150297|       12|
|  35616012|       12|
|  35917909|       11|
+----------+---------+
only showing top 5 rows

DataFrame[subject_id: int, admission_id: int, admittime: timestamp, outtime: timestamp, stay_id: int, length_of_stay: double]

In [100]:
admit_date_hospital = sql_manager.execute(spark, 'dates/admision_time.sql')
admit_date_hospital.createOrReplaceTempView("admit_date_hospital")
admit_date_hospital.show(5)
admit_time_ps = admit_date_hospital.toPandas()
admit_time_ps

+----------+------------+-------------------+
|subject_id|admission_id|          admittime|
+----------+------------+-------------------+
|  30000238|    44714428|2195-10-14 07:12:00|
|  30000246|    40653169|2104-05-05 16:18:00|
|  30000246|    43974039|2103-07-08 17:12:00|
|  30000246|    45869139|2103-07-11 10:37:00|
|  30000521|    40796332|2187-08-15 11:33:00|
+----------+------------+-------------------+
only showing top 5 rows

       subject_id  admission_id           admittime
0        30000238      44714428 2195-10-14 07:12:00
1        30000246      40653169 2104-05-05 16:18:00
2        30000246      43974039 2103-07-08 17:12:00
3        30000246      45869139 2103-07-11 10:37:00
4        30000521      40796332 2187-08-15 11:33:00
...           ...           ...                 ...
61838    39998775      48786224 2103-02-10 21:07:00
61839    39998775      49181211 2104-02-12 20:43:00
61840    39998775      49555175 2103-10-14 11:50:00
61841    39999363      44506852 2195-02-22 14:39:00
61842    39999553      45366963 2185-11-03 14:10:00

[61843 rows x 3 columns]

In [101]:
patients_data = sql_manager.execute(spark, 'initial_data/patients_filtered.sql')
patients_data.createOrReplaceTempView("patients_data")
patients_data.show(5)
patients_data_ps = patients_data.toPandas()
patients_data_ps

+----------+------------+-------------------+------+----------+------------------+
|subject_id|admission_id|          admittime|gender|anchor_age|dod_within_30_days|
+----------+------------+-------------------+------+----------+------------------+
|  30000238|    44714428|2195-10-14 07:12:00|     M|        74|              NULL|
|  30000246|    40653169|2104-05-05 16:18:00|     M|        59|              NULL|
|  30000246|    43974039|2103-07-08 17:12:00|     M|        59|              NULL|
|  30000246|    45869139|2103-07-11 10:37:00|     M|        59|              NULL|
|  30000521|    40796332|2187-08-15 11:33:00|     F|        46|              NULL|
+----------+------------+-------------------+------+----------+------------------+
only showing top 5 rows

,subject_id,admission_id,admittime,gender,anchor_age,dod_within_30_days
0,30000238,44714428,2195-10-14 07:12:00,M,74,None
1,30000246,40653169,2104-05-05 16:18:00,M,59,None
2,30000246,43974039,2103-07-08 17:12:00,M,59,None
3,30000246,45869139,2103-07-11 10:37:00,M,59,None
4,30000521,40796332,2187-08-15 11:33:00,F,46,None
...,...,...,...,...,...,...
61838,39998775,48786224,2103-02-10 21:07:00,M,75,None
61839,39998775,49181211,2104-02-12 20:43:00,M,75,None
61840,39998775,49555175,2103-10-14 11:50:00,M,75,None
61841,39999363,44506852,2195-02-22 14:39:00,F,73,None
61842,39999553,45366963,2185-11-03 14:10:00,M,69,None

In [102]:
chart_events_post_admission = sql_manager.execute(spark, 'joins/admission_chartevents.sql')
chart_events_post_admission.createOrReplaceTempView("chart_events_adm")
chart_events_post_admission.show(5)

+----------+------------+--------+-------------------+----------------+--------------------+--------------------+
|subject_id|admission_id| stay_id|          admittime|num_chart_events|       chart_itemids|        chart_values|
+----------+------------+--------+-------------------+----------------+--------------------+--------------------+
|  30000521|    46912110|58492193|2188-04-17 16:46:00|              53|[320045, 320179, ...|[92.0, 160.0, 79....|
|  30000828|    40615900|57131111|2124-10-17 23:12:00|              17|[320045, 320179, ...|[97.0, 131.0, 87....|
|  30003460|    43300755|52287466|2139-04-28 18:30:00|              47|[320045, 320050, ...|[66.0, 126.0, 58....|
|  30004640|    41454271|57661199|2128-06-04 14:14:00|             162|[320045, 320179, ...|[63.0, 127.0, 78....|
|  30006179|    40825743|57485621|2133-05-08 06:47:00|              85|[320045, 320179, ...|[79.0, 145.0, 66....|
+----------+------------+--------+-------------------+----------------+--------------------+--------------------+
only showing top 5 rows

In [103]:
lab_events_adm = sql_manager.execute(spark, 'joins/admission_labevents.sql')
lab_events_adm.createOrReplaceTempView("lab_events_adm")
lab_events_adm.show(5)
lab_events_adm_df = lab_events_adm.toPandas()
lab_events_adm_df

+----------+------------+--------+-------------------+--------------+--------------------+--------------------+
|subject_id|admission_id| stay_id|          admittime|num_lab_events|         lab_itemids|          lab_values|
+----------+------------+--------+-------------------+--------------+--------------------+--------------------+
|  30000521|    46912110|58492193|2188-04-17 16:46:00|            20|[100040, 100003, ...|[9.0, 8.0, 94.6, ...|
|  30000828|    40615900|57131111|2124-10-17 23:12:00|             0|                  []|                  []|
|  30003460|    43300755|52287466|2139-04-28 18:30:00|            22|[100046, 100003, ...|[30.7, 8.8, 1.6, ...|
|  30004640|    41454271|57661199|2128-06-04 14:14:00|            16|[100001, 100013, ...|[158.0, 223.0, 8....|
|  30006179|    40825743|57485621|2133-05-08 06:47:00|            31|[100006, 100005, ...|[23.3, 35.0, 23.1...|
+----------+------------+--------+-------------------+--------------+--------------------+--------------------+
only showing top 5 rows

,subject_id,admission_id,stay_id,admittime,num_lab_events,lab_itemids,lab_values
0,30000521,46912110,58492193,2188-04-17 16:46:00,20,"[100040, 100003, 100017, 100014, 100004, 10001...","[9.0, 8.0, 94.6, 160.0, 9.0, 23.0, 11.9, 170.0..."
1,30000828,40615900,57131111,2124-10-17 23:12:00,0,[],[]
2,30003460,43300755,52287466,2139-04-28 18:30:00,22,"[100046, 100003, 100009, 100012, 100017, 10004...","[30.7, 8.8, 1.6, 101.0, 103.0, 10.0, 34.5, 155..."
3,30004640,41454271,57661199,2128-06-04 14:14:00,16,"[100001, 100013, 100004, 100040, 100001, 10000...","[158.0, 223.0, 8.8, 1.8, 100.0, 8.0, 133.0, 23..."
4,30006179,40825743,57485621,2133-05-08 06:47:00,31,"[100006, 100005, 100034, 100018, 100007, 10001...","[23.3, 35.0, 23.1, 32.6, 7.6, 75.0, 107.0, 2.1..."
...,...,...,...,...,...,...,...
28607,39919947,44443782,51400661,2186-01-09 15:14:00,21,"[100018, 100010, 100006, 100016, 100014, 10000...","[33.9, 143.0, 38.0, 7.7, 167.0, 13.2, 12.9, 10..."
28608,39926572,45102982,56018746,2195-11-21 15:32:00,21,"[100001, 100003, 100040, 100010, 100001, 10000...","[92.0, 8.4, 8.0, 143.0, 128.0, 8.0, 0.5, 3.5, ..."
28609,39950368,45844966,57619647,2195-04-05 03:00:00,24,"[100019, 100003, 100017, 100006, 100007, 10004...","[0.0, 7.9, 87.4, 36.8, 11.7, 13.0, 4.21, 3.3, ..."
28610,39955880,43010884,53075985,2199-06-18 23:16:00,33,"[100031, 100021, 100012, 100040, 100042, 10002...","[1.1, 3.4, 94.0, 13.0, 165.0, 1.4, 4.8, 25.0, ..."
28611,39955880,43010884,56728303,2199-06-16 22:34:00,0,[],[]

In [104]:
chart_events = sql_manager.execute(spark, 'joins/icu_stays_chartevents.sql')
chart_events.createOrReplaceTempView("chart_events_icu")
lab_events = sql_manager.execute(spark, 'joins/icu_stays_labevents.sql')
lab_events.createOrReplaceTempView("lab_events_icu")
procedure_events = sql_manager.execute(spark, 'joins/icu_stays_procedure_events.sql')
procedure_events.createOrReplaceTempView("procedure_events_icu")

In [105]:
chart_events

DataFrame[subject_id: int, admission_id: int, stay_id: int, itemid: int, value: double]

In [106]:
lab_events

DataFrame[subject_id: int, admission_id: int, stay_id: int, itemid: int, value_num: double]

In [107]:
procedure_events

DataFrame[subject_id: int, admission_id: int, stay_id: int, itemid: int, value: double]

In [108]:
#86 Fº son 30 Cº y 113 Fº son 45 Cº
temperature = spark.sql("""
    select subject_id, admission_id, stay_id, max(try_cast(value as double)) as max_temp
    from chart_events_icu 
    where itemid = 323761 
        and value is not null
        and try_cast(value as double) is not null
    group by subject_id, admission_id, stay_id
""")

temperature.createOrReplaceTempView("temperature")



temperature

DataFrame[subject_id: int, admission_id: int, stay_id: int, max_temp: double]

In [109]:
systolic_arterial_bp_line = spark.sql("""
        select subject_id, admission_id, stay_id, min(value) as min_bp_systolic_line
        from chart_events_icu where itemid = 320050
            and value is not null
            and try_cast(value as double) is not null
            and try_cast(value as double) > 0
        group by subject_id, admission_id, stay_id""")
dystolic_arterial_bp_line = spark.sql("""
        select subject_id, admission_id, stay_id, min(value) as min_bp_diastolic_line
        from chart_events_icu where itemid = 320051
        group by subject_id, admission_id, stay_id""")

systolic_arterial_bp_line.createOrReplaceTempView("systolic_bp_line")
dystolic_arterial_bp_line.createOrReplaceTempView("dystolic_bp_line")

""" bp_line = systolic_arterial_bp_line.join(dystolic_arterial_bp_line,
    on=['subject_id', 'admission_id', 'stay_id'], how='full')
bp_line.createOrReplaceTempView("bp_line")
missing_bp_line = spark.sql("select * from bp_line where min_bp_systolic is null or min_bp_diastolic is null")
missing_bp_line """

bp_line = systolic_arterial_bp_line.join(dystolic_arterial_bp_line, 
    on=['subject_id', 'admission_id', 'stay_id'], how='full')
bp_line.createOrReplaceTempView("bp_line")

bp_line

DataFrame[subject_id: int, admission_id: int, stay_id: int, min_bp_systolic_line: double, min_bp_diastolic_line: double]

In [110]:
systolic_arterial_bp = spark.sql("""
        select subject_id, admission_id, stay_id, min(try_cast(value as double)) as min_bp_systolic
        from chart_events_icu where itemid = 320179
            and value is not null
            and try_cast(value as double) is not null
        group by subject_id, admission_id, stay_id""")
dystolic_arterial_bp= spark.sql("""
        select subject_id, admission_id, stay_id, min(try_cast(value as double)) as min_bp_diastolic
        from chart_events_icu where itemid = 320180
            and value is not null
            and try_cast(value as double) is not null
        group by subject_id, admission_id, stay_id""")

systolic_arterial_bp.createOrReplaceTempView("systolic_arterial_bp")
dystolic_arterial_bp.createOrReplaceTempView("dystolic_arterial_bp")


bp = systolic_arterial_bp.join(dystolic_arterial_bp,
    on=['subject_id', 'admission_id', 'stay_id'], how='full')
bp.createOrReplaceTempView("bp")


all_bp = bp_line.join(bp,
    on=['subject_id', 'admission_id', 'stay_id'], how='full')
all_bp.createOrReplaceTempView("all_bp")
all_bp

DataFrame[subject_id: int, admission_id: int, stay_id: int, min_bp_systolic_line: double, min_bp_diastolic_line: double, min_bp_systolic: double, min_bp_diastolic: double]

In [111]:
dystolic_arterial_bp

DataFrame[subject_id: int, admission_id: int, stay_id: int, min_bp_diastolic: double]

In [112]:
systolic_arterial_bp

DataFrame[subject_id: int, admission_id: int, stay_id: int, min_bp_systolic: double]

In [113]:
#Rango de valores del 0 al 100. Valores de menos del 92% se relacionan con hipoxemia grave. Limitar en rango 70-100? Se 'perderían' 354 mediciones con ese filtro
sp_o2 = spark.sql("""
        select subject_id, admission_id, stay_id, min(try_cast(value as double)) as min_oxygen_saturation
                from chart_events_icu where itemid = 320277
                    and value is not null
                    and try_cast(value as double) is not null
                group by subject_id, admission_id, stay_id""")

sp_o2.createOrReplaceTempView("sp_o2")

sp_o2

dataset_with_spo2 = all_bp.join(sp_o2,
    on=['subject_id', 'admission_id', 'stay_id'], how='full')
dataset_with_spo2.createOrReplaceTempView("dataset_with_spo2")
dataset_with_spo2

DataFrame[subject_id: int, admission_id: int, stay_id: int, min_bp_systolic_line: double, min_bp_diastolic_line: double, min_bp_systolic: double, min_bp_diastolic: double, min_oxygen_saturation: double]

In [114]:
#Rango entre 40 y 220 pulsaciones por minuto. Se 'pierden' 12 mediciones
pulse = spark.sql("""
        select subject_id, admission_id, stay_id, max(try_cast(value as double)) as max_pulse
                from chart_events_icu where itemid = 320045
                and value is not null
                and try_cast(value as double) is not null
                group by subject_id, admission_id, stay_id""")

pulse.createOrReplaceTempView("pulse")

dataset_with_pulse = dataset_with_spo2.join(pulse,
    on=['subject_id', 'admission_id', 'stay_id'], how='full')
dataset_with_pulse.createOrReplaceTempView("dataset_with_pulse")

pulse
dataset_with_pulse

DataFrame[subject_id: int, admission_id: int, stay_id: int, min_bp_systolic_line: double, min_bp_diastolic_line: double, min_bp_systolic: double, min_bp_diastolic: double, min_oxygen_saturation: double, max_pulse: double]

In [115]:
glucose = spark.sql("""
                    select subject_id, admission_id, stay_id, max(value_num) as max_glucose
                from lab_events_icu where itemid = 100001
                and value_num is not null
                group by subject_id, admission_id, stay_id""")

glucose.createOrReplaceTempView("glucose")

dataset_with_temperature = dataset_with_pulse.join(temperature, on=['subject_id', 'admission_id', 'stay_id'], how='full')

dataset_with_glucose = dataset_with_temperature.join(glucose,
    on=['subject_id', 'admission_id', 'stay_id'], how='full')   
dataset_with_glucose.createOrReplaceTempView("dataset_with_glucose")

glucose
dataset_with_glucose

DataFrame[subject_id: int, admission_id: int, stay_id: int, min_bp_systolic_line: double, min_bp_diastolic_line: double, min_bp_systolic: double, min_bp_diastolic: double, min_oxygen_saturation: double, max_pulse: double, max_temp: double, max_glucose: double]

In [116]:
lactate = spark.sql("""
                    select subject_id, admission_id, stay_id, max(value_num) as max_lactate
                from lab_events_icu where itemid = 100031
                and value_num is not null
                group by subject_id, admission_id, stay_id""")

lactate.createOrReplaceTempView("lactate")

In [117]:
procedure_flags = sql_manager.execute(spark, 'joins/procedure_flags.sql')
procedure_flags.createOrReplaceTempView("procedure_flags")

In [ ]:

base_stays = spark.sql("""
    SELECT DISTINCT i.subject_id, i.admission_id, i.stay_id, i.length_of_stay
    FROM icu_stays_data i
    INNER JOIN diagnoses_icd d ON i.subject_id = d.subject_id AND i.admission_id = d.hadm_id
    WHERE d.icd_code = 'U071'
""")

dataset_complete = (base_stays
    .join(all_bp, on=['subject_id', 'admission_id', 'stay_id'], how='left')
    .join(sp_o2, on=['subject_id', 'admission_id', 'stay_id'], how='left')
    .join(pulse, on=['subject_id', 'admission_id', 'stay_id'], how='left')
    .join(temperature, on=['subject_id', 'admission_id', 'stay_id'], how='left')
    .join(glucose, on=['subject_id', 'admission_id', 'stay_id'], how='left')
    .join(lactate, on=['subject_id', 'admission_id', 'stay_id'], how='left')
    .join(procedure_flags, on=['subject_id', 'admission_id', 'stay_id'], how='left')
    .join(patients_data.select('subject_id', 'admission_id', 'gender', 'anchor_age', 'dod_within_30_days'), 
          on=['subject_id', 'admission_id'], how='left')
    .join(hosp_adm_data.select('subject_id', 'admission_id', 'marital_status', 'race'), 
          on=['subject_id', 'admission_id'], how='left')
)

procedure_columns = ['is_mechanical_ventilation', 'is_crrt', 'has_arterial_line', 
                     'is_intubated', 'is_prone_position', 'has_chest_tube', 
                     'is_dnr', 'has_central_line', 'has_hemodialysis', 
                     'has_niv', 'is_ecmo']

for col_name in procedure_columns:
    dataset_complete = dataset_complete.fillna({col_name: 0})

dataset_complete.createOrReplaceTempView("dataset_complete")

print(f"Total de stays en base: {base_stays.count()}")
print(f"Total de stays en dataset final: {dataset_complete.count()}")
dataset_complete.show(5)

dataset_complete.write.mode("overwrite").csv("../data/processed/covid_icu_dataset.csv", header=True)
dataset_complete.write.mode("overwrite").parquet("../data/processed/covid_icu_dataset.parquet")

dataset_complete

Total de stays en base: 28612

Total de stays en dataset final: 28612

26/02/02 17:48:36 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 1 retries)
java.io.IOException: Failed to connect to /192.168.1.38:63741
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:305)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:225)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Operation timed out: /192.168.1.38:63741
Caused by: java.net.ConnectException: Operation timed out
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:784)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:48:36 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.start(RetryingBlockTransferor.java:160)
	at org.apache.spark.network.netty.NettyBlockTransferService.fetchBlocks(NettyBlockTransferService.scala:157)
	at org.apache.spark.network.BlockTransferService.fetchBlockSync(BlockTransferService.scala:102)
	at org.apache.spark.storage.BlockManager.fetchRemoteManagedBuffer(BlockManager.scala:1203)
	at org.apache.spark.storage.BlockManager.$anonfun$getRemoteBlock$8(BlockManager.scala:1147)
	at scala.Option.orElse(Option.scala:477)
	at org.apache.spark.storage.BlockManager.getRemoteBlock(BlockManager.scala:1147)
	at org.apache.spark.storage.BlockManager.getRemoteBytes(BlockManager.scala:1290)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.$anonfun$run$1(TaskResultGetter.scala:89)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.run(TaskResultGetter.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:48:36 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 1 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:48:36 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 1 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:49:56 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 2 retries)
java.io.IOException: Failed to connect to /192.168.1.38:63741
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:305)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:225)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Operation timed out: /192.168.1.38:63741
Caused by: java.net.ConnectException: Operation timed out
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:784)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:49:56 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 2 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:49:56 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 2 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:49:56 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 1 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:51:16 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 3 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:51:16 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 2 retries)
java.io.IOException: Failed to connect to /192.168.1.38:63741
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:305)
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:225)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Operation timed out: /192.168.1.38:63741
Caused by: java.net.ConnectException: Operation timed out
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:336)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:784)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:732)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:51:16 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 3 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:51:16 ERROR RetryingBlockTransferor: Exception while beginning fetch of 1 outstanding blocks (after 3 retries)
java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
26/02/02 17:51:16 WARN BlockManager: Failed to fetch remote block taskresult_2774 from [BlockManagerId(driver, 192.168.1.38, 63741, None)] after 1 fetch failures. Most recent failure cause:
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.network.BlockTransferService.fetchBlockSync(BlockTransferService.scala:103)
	at org.apache.spark.storage.BlockManager.fetchRemoteManagedBuffer(BlockManager.scala:1203)
	at org.apache.spark.storage.BlockManager.$anonfun$getRemoteBlock$8(BlockManager.scala:1147)
	at scala.Option.orElse(Option.scala:477)
	at org.apache.spark.storage.BlockManager.getRemoteBlock(BlockManager.scala:1147)
	at org.apache.spark.storage.BlockManager.getRemoteBytes(BlockManager.scala:1290)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.$anonfun$run$1(TaskResultGetter.scala:89)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.scheduler.TaskResultGetter$$anon$3.run(TaskResultGetter.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: Connecting to /192.168.1.38:63741 failed in the last 4750 ms, fail this connection directly
	at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:221)
	at org.apache.spark.network.netty.NettyBlockTransferService$$anon$2.createAndStart(NettyBlockTransferService.scala:137)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.transferAllOutstanding(RetryingBlockTransferor.java:181)
	at org.apache.spark.network.shuffle.RetryingBlockTransferor.lambda$initiateRetry$0(RetryingBlockTransferor.java:228)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
26/02/02 17:51:16 WARN BlockManager: Failed to fetch remote block taskresult_2771 from [BlockManagerId(driver, 192.168.1.38, 63741, None)] after 1 fetch failures. Most recent failure cause:
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.network.BlockTransferService.fetchBlockSync(BlockTransferService.scala:103)
	at org.apache.spark.storage.BlockManager.fetchRemoteManagedBuffer(BlockManager.scala:1203)
	at org.apache.spark.storage.BlockManager.$anonfun$getRemoteBlock$8(BlockManager.scala:1147)

Py4JJavaError: An error occurred while calling o1846.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 1626.0 failed 1 times, most recent failure: Lost task 1.0 in stage 1626.0 (TID 3021) (192.168.1.38 executor driver): TaskResultLost (result lost from block manager)
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$3(DAGScheduler.scala:2935)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2935)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2927)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2927)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1295)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1295)
	at scala.Option.foreach(Option.scala:437)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1295)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3207)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3141)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3130)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:50)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1009)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2484)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2505)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2524)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2549)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1057)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:417)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1056)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectIterator(SparkPlan.scala:469)
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec.$anonfun$relationFuture$1(BroadcastExchangeExec.scala:182)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$4(SQLExecution.scala:322)
	at org.apache.spark.sql.execution.SQLExecution$.withSessionTagsApplied(SQLExecution.scala:272)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$3(SQLExecution.scala:320)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$2(SQLExecution.scala:316)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

In [9]:
admissions_with_valid_dod = spark.sql("""
    select * from hosp_adm_data 
    where deathtime is not null 
    and deathtime <= dischtime
    and deathtime > admittime""")

admissions_with_valid_dod

DataFrame[subject_id: int, admission_id: int, marital_status: string, race: string, admittime: timestamp, dischtime: timestamp, deathtime: timestamp, hosp_outcome: void]